vesion: "3.7"
services:
   webserver:
      image: leeseohyeon/chat:latest
      deploy:
         replicas: 4
         placement:
            constraints: [node.role != manager]
      ports:
         - 8080:80